### ISSUE TITLE
Graceful handling of native library assertion failures

### ISSUE THREAD

**Issue by scatterlogical** [HexaEngine/Hexa.NET.ImGui#35]
Would it be possible to more gracefully handle assertion failures etc. from the native imgui library, instead of just crashing with a message to console? 

This approach can be
A. difficult to debug, since there's limited information linking the error back to managed code
B. difficult to develop with - if I'm live coding and hot reload, it's frustrating and time consuming every time I make a mistake and I have to restart the app) 
C. potentially detrimental to the stability of releases, since there is no way to intercept these crashes from managed code.

Imgui.net handles these situations a lot more gracefully. I can't recall how exactly, been a while since I was using it, but I know that I wasn't having to reload my game every 30 secs as I figure out how to use some part of imgui that I haven't explored before.

Throwing exceptions would be the obvious and established choice. Give the dev a chance to trace their mistake.
Simply logging to console without crashing is second best, but this doesn't provide clear tracing - this might still be acceptable since the assertions are usually in code that is currently being worked on.

**Comment by JunaMeinhold** [comment]
Hi, you can activate Mixed Mode debugging that shows you the call stack or by disabling assertions in the io debug settings, the red boxed will still show up.

**Comment by JunaMeinhold** [comment]
The main reason why this happens with the crash is because the binaries are in Release build profile, optimising for performance but this also breaks the assertion window.

**Comment by JunaMeinhold** [comment]
You can enable mixed mode debugging like this in visual studio:
![Image](https://github.com/user-attachments/assets/3b2f6ea7-de5e-4dd5-a1cf-cb1007bb56ae)

![Image](https://github.com/user-attachments/assets/05d9cd58-5820-4aa7-a032-8a5e9da5cfe7)

**Comment by JunaMeinhold** [comment]
One solution would be this config, but i can't re-throw native exceptions they work differently from managed. 
```cs
  var io = ImGui.GetIO();
  io.ConfigErrorRecovery = true;
  io.ConfigErrorRecoveryEnableAssert = false; // prevents throwing native errors.
  io.ConfigErrorRecoveryEnableTooltip = true; // shows red boxes on errors on the exact UI component that causes problems, note some error are not recoverable, like buffer overflows.
  io.ConfigDebugIsDebuggerPresent = Debugger.IsAttached;
```

**Comment by sonoro1234** [comment]
> The main reason why this happens with the crash is because the binaries are in Release build profile, optimising for performance but this also breaks the assertion window.

This is the purpose of this commit https://github.com/cimgui/cimgui/commit/fdd07821bbcc6583431fd42ad3ffad3a82e69501
comming from this conversation https://github.com/ocornut/imgui/issues/8078

**Comment by JunaMeinhold** [comment]
Then this should be fixed with 2.2.5, (ImGui 1.91.7)

**Comment by sonoro1234** [comment]
It is a build cmake setting. I am not sure how you build.

**Comment by JunaMeinhold** [comment]
I build it in github actions
Here https://github.com/HexaEngine/Hexa.NET.ImGui/actions/runs/12964989371
With a fork of your repo
https://github.com/JunaMeinhold/cimgui

**Comment by scatterlogical** [comment]
> One solution would be this config, but i can't re-throw native exceptions they work differently from managed.
> 
>   var io = ImGui.GetIO();
>   io.ConfigErrorRecovery = true;
>   io.ConfigErrorRecoveryEnableAssert = false; // prevents throwing native errors.
>   io.ConfigErrorRecoveryEnableTooltip = true; // shows red boxes on errors on the exact UI component that causes problems, note some error are not recoverable, like buffer overflows.
>   io.ConfigDebugIsDebuggerPresent = Debugger.IsAttached;
> 
> like this
> 
> ![Image](https://github.com/user-attachments/assets/6eaba4c3-88ef-4477-9df3-c89f1a8f200d)

Thanks, I have enabled these configs and it helps with the more minor errors.

**Comment by paulbartrum** [comment]
FYI for anyone still experiencing app termination due to hitting ImGui assertions (and who doesn't want to use mixed mode debugging), use this code to show an error dialog instead:
```c#
// By default the Visual C++ runtime library seems to consider .NET apps to be console apps (presumably
// because the UCRT code to detect the app type didn't run) and thus a message box is not shown when
// assert() is triggered. This is important for ImGui, which uses IM_ASSERT() liberally.
// By calling _set_error_mode we can force the message box to be shown.
const int _OUT_TO_MSGBOX = 2;
_ = _set_error_mode(_OUT_TO_MSGBOX);

/// <summary>
/// Specifies the behavior of the assert() function in the Visual C++ runtime library.
/// </summary>
/// <param name="mode_val"> An enum value that specifies the desired behavior. </param>
/// <returns> The old setting or <c>-1</c> if an error occurs. </returns>
[DllImport("ucrtbase.dll", CallingConvention = CallingConvention.Cdecl)]
private static extern int _set_error_mode(int mode_val);
```

Pros:
- Works even without a debugger attached.
- Shows the exact assertion condition that triggered.

Cons:
- The "retry" option, which is supposed to launch the debugger, didn't work for me.
- Ignore is usually useless since the assertion will just trigger again next frame.
